/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as IndexImport } from './routes/index'
import { Route as LayoutProductsImport } from './routes/_layout/products'
import { Route as LayoutProductsIndexImport } from './routes/_layout/products.index'
import { Route as LayoutProductProductIdImport } from './routes/_layout/product.$productId'
import { Route as LayoutProductsProductIdModalImport } from './routes/_layout/products._.$productId.modal'

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LayoutProductsRoute = LayoutProductsImport.update({
  path: '/products',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutProductsIndexRoute = LayoutProductsIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutProductsRoute,
} as any)

const LayoutProductProductIdRoute = LayoutProductProductIdImport.update({
  path: '/product/$productId',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutProductsProductIdModalRoute =
  LayoutProductsProductIdModalImport.update({
    path: '/$productId/modal',
    getParentRoute: () => LayoutProductsRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_layout': {
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/products': {
      preLoaderRoute: typeof LayoutProductsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/product/$productId': {
      preLoaderRoute: typeof LayoutProductProductIdImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/products/': {
      preLoaderRoute: typeof LayoutProductsIndexImport
      parentRoute: typeof LayoutProductsImport
    }
    '/_layout/products//$productId/modal': {
      preLoaderRoute: typeof LayoutProductsProductIdModalImport
      parentRoute: typeof LayoutProductsImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  LayoutRoute.addChildren([
    LayoutProductsRoute.addChildren([
      LayoutProductsIndexRoute,
      LayoutProductsProductIdModalRoute,
    ]),
    LayoutProductProductIdRoute,
  ]),
])

/* prettier-ignore-end */
