/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as IndexImport } from './routes/index'
import { Route as LayoutProductsIndexImport } from './routes/_layout/products.index'
import { Route as LayoutProductsProductIdImport } from './routes/_layout/products.$productId'
import { Route as LayoutProductsProductIdModalImport } from './routes/_layout/products._.$productId.modal'

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LayoutProductsIndexRoute = LayoutProductsIndexImport.update({
  path: '/products/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutProductsProductIdRoute = LayoutProductsProductIdImport.update({
  path: '/products/$productId',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutProductsProductIdModalRoute =
  LayoutProductsProductIdModalImport.update({
    path: '/products/$productId/modal',
    getParentRoute: () => LayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_layout': {
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/products/$productId': {
      preLoaderRoute: typeof LayoutProductsProductIdImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/products/': {
      preLoaderRoute: typeof LayoutProductsIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/products//$productId/modal': {
      preLoaderRoute: typeof LayoutProductsProductIdModalImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  LayoutRoute.addChildren([
    LayoutProductsProductIdRoute,
    LayoutProductsIndexRoute,
    LayoutProductsProductIdModalRoute,
  ]),
])

/* prettier-ignore-end */
